export const ADD_USER_DETAILS_REQUEST = "ADD_USER_DETAILS_REQUEST";
export const ADD_USER_DETAILS_REQUEST_SUCCESS =
  "ADD_USER_DETAILS_REQUEST_SUCCESS";
export const ADD_USER_DETAILS_REQUEST_FAILED =
  "ADD_USER_DETAILS_REQUEST_FAILED";

export const GET_USER_DETAILS_REQUEST = "ADD_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_REQUEST_SUCCESS =
  "ADD_USER_DETAILS_REQUEST_SUCCESS";
export const GET_USER_DETAILS_REQUEST_FAILED =
  "ADD_USER_DETAILS_REQUEST_FAILED";
